language: cpp

dist: bionic

env:
  - EVAL="CXX=g++"
  - EVAL="CXX=clang++"

addons:
  apt:
    sources:
      - sourceline: 'ppa:openmw/openmw'
    packages:
      - zlib1g-dev
      - libbullet-dev
      - libopenal-dev
      - libglm-dev
      - libopenscenegraph-3.4-dev

before_install:
  - eval "${EVAL}"

script:
- mkdir build
- cd build
- cmake ..
- make -j 2
